MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
    MIN_SIZE: 16
  BACKBONE:
    CONV_BODY: "R-50-C4"
  ROI_BOX_HEAD:
    NUM_CLASSES: 14
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
  TRANSFORMER:
    USE_TRANS: True
    TYPE: "CP"
    POOL_SIZES: [6,3,2,1]
    KERNEL_SIZES: [1,3,5,9]
    RATES: [1,6,12,18]
DATASETS:
  TRAIN: ("voc_rm_train",)
  TEST: ("voc_rm_test",)
SOLVER:
  BASE_LR: 0.008
  WEIGHT_DECAY: 0.0005
  STEPS: (5663,)
  MAX_ITER: 8090
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
  FLIP_PROB_TRAIN: 0.0
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "./output/rm_e2e_faster_rcnn_18"